# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22896c26c37de9336b249f3a981c5f49b6a59a095f4c409292fea060aa5ccb23f982e8767887c1573fc68a2496a99893c48647b624da098a2d334f9e15c93ba1

test:
  secret_key_base: 6c884bd038d43f09b1f97d819fa772cd0b1b3a0018a5589c9c59c16f6d30752170fed54817c9a44df72b9d54596b882e9346d630343e46be71e735e3c0fb0638

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
